# Generated by Django 4.2.1 on 2023-06-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_questioncategory_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
