# Generated by Django 4.2.1 on 2023-06-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_alter_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizcategory",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="categories",
        ),
        migrations.AddField(
            model_name="quiz",
            name="categories",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizes",
                to="quiz.quizcategory",
            ),
        ),
    ]
