# Generated by Django 4.2.1 on 2023-06-17 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0007_quizcategory_updated_remove_quiz_categories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="categories",
            new_name="category",
        ),
        migrations.AddField(
            model_name="quizinstance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quizinstance",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="quiz.quiz",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizinstance",
            unique_together={("quiz", "user")},
        ),
    ]
