# Generated by Django 4.2.1 on 2023-06-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_quizinstance_unique_together_quiz_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
