# Generated by Django 4.2.1 on 2023-07-06 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiz_allowed_grades_quiz_grouped_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestiongroup',
            name='order_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='quizquestiongroup',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
