# Generated by Django 4.2.1 on 2023-07-10 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('quiz', '0012_quizquestiongroup_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='allowed_grades',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='allowed_users',
        ),
        migrations.CreateModel(
            name='AllowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_quizes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('quiz', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AllowedGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_quizes', to='account.grade')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_grades', to='quiz.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'grade')},
            },
        ),
    ]
