# Generated by Django 4.2.1 on 2023-07-18 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0015_alter_question_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizinstanceoption',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userattempt',
            name='quiz_instance',
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizinstanceoption',
            name='question_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizinstancequestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userattempt',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userattempt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizinstancequestion',
            name='quiz_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_questions', to='quiz.userattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='quizinstanceoption',
            unique_together={('question_instance', 'option')},
        ),
        migrations.RemoveField(
            model_name='quizinstanceoption',
            name='quiz_instance',
        ),
        migrations.DeleteModel(
            name='QuizInstance',
        ),
    ]
