# Generated by Django 4.2.1 on 2023-07-19 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_quizinstanceoption_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizinstanceoption',
            name='question_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.quizinstancequestion'),
        ),
    ]
