# Generated by Django 4.2.3 on 2023-07-20 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_quizinstanceoption_question_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('start_time',)},
        ),
        migrations.AddField(
            model_name='userattempt',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
