# Generated by Django 4.2.3 on 2023-07-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterField(
            model_name='userattempt',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userattempt',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
