# Generated by Django 4.2.3 on 2023-07-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_questionoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizinstanceoption',
            options={'ordering': ['option_order']},
        ),
        migrations.AlterModelOptions(
            name='quizinstancequestion',
            options={'ordering': ['question_order']},
        ),
    ]
